### ISSUE TITLE
Great job!

### ISSUE THREAD

**Issue by JaDenis** [davidaparicio/swarm-ollama#2] opened 2024-10-20 17:26 UTC
Thank you for your hard work! This is exactly what I wanted.

I get an error though: 
`Traceback (most recent call last):
  File "/Users/m1/Downloads/swarm-ollama-main/examples/basic_ollama/example.py", line 21, in <module>
    response = client.run(
               ^^^^^^^^^^^
  File "/Users/m1/.pyenv/versions/3.12.7/lib/python3.12/site-packages/swarm_ollama/core.py", line 305, in run
    completion = self.get_chat_completion(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m1/.pyenv/versions/3.12.7/lib/python3.12/site-packages/swarm_ollama/core.py", line 114, in get_chat_completion
    return self.client.chat.completions.create(**create_params)
           ^^^^^^^^^^^
AttributeError: 'Swarm' object has no attribute 'client'`

Here is python code I'm executing: 
```python
from swarm_ollama import Swarm, Agent

#client = Swarm()
client = Swarm(base_url="http://localhost:11434")

def transfer_to_agent_b():
    return agent_b


agent_a = Agent(
    name="Agent A",
    instructions="You are a helpful agent.",
    functions=[transfer_to_agent_b],
)

agent_b = Agent(
    name="Agent B",
    instructions="Only speak in Haikus.",
)

response = client.run(
    agent=agent_a,
    messages=[{"role": "user", "content": "I want to talk to agent B."}],
)

print(response.messages[-1]["content"])
```

I got Ollama running Llama3.2:3b and installed swarm_ollama like you instructed in Readme.md

**Comment by JaDenis** [comment] 2024-10-21 11:41
bump
had no luck so far, trying different stuff

**Comment by davidaparicio** [comment] 2024-10-21 16:29
Hello @JaDenis! I'm sorry, I forgot to set the repo as private.
I'm currently fixing this issue 👍

**Comment by davidaparicio** [comment] 2024-10-21 19:58
It fixed here.

```python3
❯ PYTHONPATH=. python3 examples/basic_ollama/function_calling.py
The weather in NYC is ["{'temp':67, 'unit':'F'}"]

❯ PYTHONPATH=. python3 examples/basic_ollama/agent_handoff.py
 ¿En qué puedo ayudarte hoy?

swarm-ollama on  main is 📦 v0.1.0 via 🐍 v3.13.0 (swarm-ollama)
❯ PYTHONPATH=. python3 examples/basic_ollama/agent_handoff.py

swarm-ollama on  main is 📦 v0.1.0 via 🐍 v3.13.0 (swarm-ollama)
❯ PYTHONPATH=. python3 examples/basic_ollama/agent_handoff.py
¿En qué puedo ayudarle?
```

Can you confirm @JaDenis?

**Comment by JaDenis** [comment] 2024-10-23 08:56
Hi!
My bad for taking so long!

did 
```
pip uninstall swarm_ollama
pip install git+https://git@github.com/davidaparicio/swarm-ollama.git
```

got new error:
```
Traceback (most recent call last):
  File "/Users/m1/Downloads/swarm-ollama-main-2/examples/basic_ollama/bare_minimum.py", line 12, in <module>
    response = client.run(agent=agent, messages=messages)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m1/.pyenv/versions/3.12.7/lib/python3.12/site-packages/swarm_ollama/core.py", line 269, in run
    completion = self.get_chat_completion(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m1/.pyenv/versions/3.12.7/lib/python3.12/site-packages/swarm_ollama/core.py", line 83, in get_chat_completion
    return self.client.chat.completions.create(**create_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m1/.pyenv/versions/3.12.7/lib/python3.12/site-packages/swarm_ollama/wrapper.py", line 22, in create
    response = self.client.chat(**ollama_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m1/.pyenv/versions/3.12.7/lib/python3.12/site-packages/ollama/_client.py", line 236, in chat
    return self._request_stream(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m1/.pyenv/versions/3.12.7/lib/python3.12/site-packages/ollama/_client.py", line 99, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/m1/.pyenv/versions/3.12.7/lib/python3.12/site-packages/ollama/_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError```
`

Maybe I should do something else?
appreciate the effort, dude!)

**Comment by davidaparicio** [comment] 2024-10-25 19:08
Weird, unfortunately, I can't reproduce here.. :(

```python
❯ PYTHONPATH=. python3 examples/basic_ollama/bare_minimum.py
Hello! How can I assist you today? Do you have any questions, need help with something, or just want to chat?
```

Which ollama models have you?

Here, I have currently these ones:

```bash
❯ ollama list
NAME                       ID              SIZE      MODIFIED
tinyllama:1.1b             2644915ede35    637 MB    3 days ago
llama3.2:3b                a80c4f17acd5    2.0 GB    3 days ago
nomic-embed-text:latest    0a109f422b47    274 MB    8 days ago
tinyllama:latest           2644915ede35    637 MB    8 days ago
llama3.2:latest            a80c4f17acd5    2.0 GB    8 days ago
mixtral:latest             d39eb76ed9c5    26 GB     6 weeks ago
codestral:latest           0898a8b286d5    12 GB     6 weeks ago
```

**Comment by davidaparicio** [comment] 2024-10-25 21:36
Following your stacktrace, the possible causes are:

* Ollama Server Not Running (```ollama serve```):
  * The Ollama server might not be running locally, causing connection attempts to fail.

* Model Not Available (```ollama list```):
  * The model you're trying to use may not be installed or correctly specified.

Snippet from the example code
```Python
agent = Agent(
    model="llama3.2:3b",
    name="Agent",
    instructions="You are a helpful agent.",
)
```

Have you ```llama3.2:3b``` in our laptop?
You download it with ```ollama pull llama3.2:3b``` or change the model in the example file ;)

**Comment by davidaparicio** [comment] 2024-10-26 08:23
I reproduce this one:

```python
❯ PYTHONPATH=. python3 examples/basic_ollama/ollama-example.py
Traceback (most recent call last):
  File "/Users/daparicio/code/github.com/davidaparicio/swarm-ollama/swarm_ollama/wrapper.py", line 52, in create
    response = self.client.chat(**ollama_kwargs)
  File "/Users/daparicio/code/github.com/davidaparicio/swarm-ollama/.venv/lib/python3.13/site-packages/ollama/_client.py", line 236, in chat
    return self._request_stream(
           ~~~~~~~~~~~~~~~~~~~~^
      'POST',
      ^^^^^^^
    ...<10 lines>...
      stream=stream,
      ^^^^^^^^^^^^^^
    )
    ^
  File "/Users/daparicio/code/github.com/davidaparicio/swarm-ollama/.venv/lib/python3.13/site-packages/ollama/_client.py", line 99, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
                                                        ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/daparicio/code/github.com/davidaparicio/swarm-ollama/.venv/lib/python3.13/site-packages/ollama/_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: model "llama3.2:1b" not found, try pulling it first

During handling of the above exception, another exception occurred:
```

**Comment by davidaparicio** [comment] 2024-10-26 09:27
I have just pushed some error handling for the wrapper to get an easier error message.
Can you, @JaDenis, try with the new version in order to help you ? 👍

**Comment by JaDenis** [comment] 2024-10-28 08:47
Hi, David!
You did it, it's working with Ollama offline, with this code:
```python 
from swarm_ollama import Swarm, Agent

# client = Swarm()
## IF NEEDED, you change surcharge the base_url with the OLLAMA_URL
client = Swarm(base_url="http://localhost:11434")

def transfer_to_agent_b():
    return agent_b


agent_a = Agent(
    name="Agent A",
    model="llama3.2",
    instructions="You are a helpful agent.",
    functions=[transfer_to_agent_b],
)

agent_b = Agent(
    name="Agent B",
    model="llama3.2",
    instructions="Only speak in Haikus.",
)

response = client.run(
    agent=agent_a,
    messages=[{"role": "user", "content": "I want to talk to agent B."}],
)

print(response.messages[-1]["content"])
```

After trying like 20 different prompts I've noticed it never used agent B, just agent A yapping about he's not Agent B, but he can pretend to be one)

**Comment by davidaparicio** [comment] 2024-10-29 11:40
Hi @JaDenis,

You're true: tinyllama:1.1b does not support tools

I handle the tool support in the next wrapper version https://github.com/davidaparicio/swarm-ollama/pull/3 👍 
And I fixed the README/usage.py example.

Now, it's working:

```
❯ PYTHONPATH=. python3 examples/basic/usage.py
Silent screen appears
Messages for Agent B wait
Secrets are revealed

❯ PYTHONPATH=. python3 examples/basic/usage.py
Whispers in the dark
Echoes of a secret past
Shadows softly fall

❯ PYTHONPATH=. python3 examples/basic/usage.py
Silent screen appears
Messages on screen now read
Agent B is here
```

Thanks a lot for your useful feedback!!

Kind regards,
David

**Comment by JaDenis** [comment] 2024-10-31 08:51
all_in_one.py example is working fine, you the man, David!)

**Comment by davidaparicio** [comment] 2024-10-31 21:45
Thanks a lot for your feedback!!! 🥇 
So I can close this issue 👍

**Closed as completed by davidaparicio** 2024-10-31 21:45 UTC
